# [START django_app]
# [START gaestd_py_django_app_yaml]
runtime: python

runtime_config:
    python_version: 3.7

# instance_class: F4
env: flex
entrypoint: gunicorn -b :$PORT compo_server.wsgi

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 3
    cool_down_period_sec: 180
    cpu_utilization:
        target_utilization: 0.9
resources:
    cpu: 1
    memory_gb: 2
    disk_size_gb: 10
# readiness_check:
#   app_start_timeout_sec: 1800
# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 100
#   cpu_utilization:
#     target_utilization: 0.9

beta_settings:
    cloud_sql_instances: composite-353517:europe-west6:compodb

env_variables:
  # This setting is used in settings.py to configure your ALLOWED_HOSTS
  # APPENGINE_URL: https://api.composite.digital
  DEBUG: False



# handlers:
# # This configures Google App Engine to serve the files in the app's static
# # directory.
# - url: /static
#   static_dir: static/

# # This handler routes all requests not caught above to your main app. It is
# # required when static routes are defined, but can be omitted (along with
# # the entire handlers section) when there are no static files defined.
# - url: /.*
#   script: auto
# # [END gaestd_py_django_app_yaml]
# # [END django_app]