# Generated by Django 4.0 on 2022-06-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='accomplishment',
            name='file',
            field=models.FileField(null=True, upload_to='accomplishments/'),
        ),
        migrations.AlterField(
            model_name='accomplishment',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisationuser',
            name='admin_user',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='organisationuser',
            name='analytics_user',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='organisationuser',
            name='curator_user',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='organisationuser',
            name='marketing_user',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='organisationuser',
            name='publisher_user',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='file',
            field=models.FileField(null=True, upload_to='recommendations/'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='desired_degree',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='desired_job',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='desired_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
