# Generated by Django 3.2.13 on 2022-07-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_desired_job_student_desired_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graduated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
