# Generated by Django 3.2.13 on 2022-07-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_graduated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_onboarded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
