import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from '../components/Navbar/Navbar';
import Banner from '../components/Banner/Banner';
import About from '../components/aboutSection/About';
import Offers from '../components/offersSection/Offers';
import University from '../components/universitySection/University';
import Tools from '../components/toolSection/Tools';
import Degree from '../components/degreeSection/Degree';
import Review from '../components/reviewSection/Review';
import Subscriber from '../components/subscriberSection/Subscriber';
import Footer from '../components/Footer/Footer';
export default function Home() {
  return (
    <div >
      <Head>
        <title>Composite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <Banner/>
      <About/>
      <Offers/>
      <University/>
      <Tools/>
      <Degree/>
      <Review/>
      <Subscriber />
      
      
<Footer/>
      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
