import Head from "next/head";
import NavBar from "../components/Navbar/Navbar";
import Banner from "../components/Banner/Banner";
import About from "../components/aboutSection/About";
import Offers from "../components/offersSection/Offers";
import University from "../components/universitySection/University";
import Tools from "../components/toolSection/Tools";
import Degree from "../components/degreeSection/Degree";
import Review from "../components/reviewSection/Review";
import Subscriber from "../components/subscriberSection/Subscriber";
import Footer from "../components/Footer/Footer";

function Home() {
  return (
    <>
      <Head>
        <title>Composite</title>
        <meta name="description" content="Generated by Mahad Bajwa" />
      </Head>
      <NavBar />
      <Banner />
      <About />
      <Offers />
      <University />
      <Tools />
      <Degree />
      <Review />
      <Subscriber />
      <Footer />
    </>
    
  );
}


export default Home;