# Generated by Django 4.0.4 on 2022-06-16 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('UAE_Ranking', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='university_images/')),
                ('description', models.TextField(blank=True)),
                ('institute_type', models.CharField(blank=True, max_length=200)),
                ('campus_settings', models.CharField(blank=True, max_length=200)),
                ('student_body_size', models.IntegerField(default=0)),
                ('prince_range', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('field', models.CharField(blank=True, max_length=200)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('renewable', models.BooleanField(default=False)),
                ('competition_level', models.CharField(blank=True, max_length=200)),
                ('effort_level', models.CharField(blank=True, max_length=200)),
                ('num_awards_granted', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('degree_level', models.CharField(blank=True, max_length=200)),
                ('years_of_study', models.IntegerField(default=0)),
                ('format_name', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(blank=True, max_length=200)),
                ('schedule', models.CharField(blank=True, max_length=200)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.university')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('headline', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
