# Generated by Django 4.0.4 on 2022-06-18 21:11

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='name', unique=True)),
                ('rank', models.CharField(blank=True, max_length=200)),
                ('rank_order', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, upload_to='university_images/')),
                ('description', models.TextField(blank=True)),
                ('institute_type', models.CharField(blank=True, max_length=200)),
                ('campus_settings', models.CharField(blank=True, max_length=200)),
                ('student_body_size', models.IntegerField(default=0)),
                ('prince_range', models.CharField(blank=True, max_length=200)),
                ('scores_overall', models.FloatField(blank=True, null=True)),
                ('scores_overall_rank', models.FloatField(blank=True, null=True)),
                ('scores_teaching', models.FloatField(blank=True, null=True)),
                ('scores_teaching_rank', models.FloatField(blank=True, null=True)),
                ('scores_research', models.FloatField(blank=True, null=True)),
                ('scores_research_rank', models.FloatField(blank=True, null=True)),
                ('scores_citations', models.FloatField(blank=True, null=True)),
                ('scores_citations_rank', models.FloatField(blank=True, null=True)),
                ('scores_industry_income', models.FloatField(blank=True, null=True)),
                ('scores_industry_income_rank', models.FloatField(blank=True, null=True)),
                ('scores_international_outlook', models.FloatField(blank=True, null=True)),
                ('scores_international_outlook_rank', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('stats_student_staff_ratio', models.FloatField(blank=True, null=True)),
                ('stats_pc_intl_students', models.CharField(blank=True, max_length=50, null=True)),
                ('stats_female_male_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('subjects_offered', models.TextField(blank=True, null=True)),
                ('closed', models.BooleanField(blank=True, default=False, null=True)),
                ('unaccredited', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('field', models.CharField(blank=True, max_length=200, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('renewable', models.BooleanField(blank=True, default=False, null=True)),
                ('competition_level', models.CharField(blank=True, max_length=200, null=True)),
                ('effort_level', models.CharField(blank=True, max_length=200, null=True)),
                ('num_awards_granted', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('degree_level', models.CharField(blank=True, max_length=200, null=True)),
                ('years_of_study', models.IntegerField(default=0)),
                ('format_name', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('schedule', models.CharField(blank=True, max_length=200, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.university')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='title', unique=True)),
                ('headline', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
