# Generated by Django 3.2.13 on 2022-07-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20220706_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='contact_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='email',
            field=models.EmailField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='host_institution',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='includes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='nationality_requirements',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='phone',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
