# Generated by Django 3.2.13 on 2022-08-17 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20220708_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('score', models.FloatField(null=True)),
                ('no_req', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_deadline', models.CharField(blank=True, max_length=200, null=True)),
                ('deadline_type', models.CharField(blank=True, max_length=200, null=True)),
                ('apply_anytime', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, null=True)),
                ('duration', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('rank', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='program',
            name='application_deadline',
        ),
        migrations.RemoveField(
            model_name='program',
            name='degree_level',
        ),
        migrations.RemoveField(
            model_name='program',
            name='format_name',
        ),
        migrations.RemoveField(
            model_name='program',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='program',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='program',
            name='years_of_study',
        ),
        migrations.AddField(
            model_name='program',
            name='credits',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='delivered',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='link_to_website',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='living_cost_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='living_cost_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='other_requirements',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='program_structure',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='tuition_fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='tuition_fee_currency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='tuition_fee_duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='about_sp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='description_sp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='maps_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='sp_bachelors',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='sp_masters',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='sp_phd',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='student_life',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.university'),
        ),
        migrations.AlterField(
            model_name='university',
            name='student_body_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=200, null=True)),
                ('application_deadlines', models.ManyToManyField(to='directory.ApplicationDeadline')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='academic_requirements',
            field=models.ManyToManyField(to='directory.AcademicRequirement'),
        ),
        migrations.AddField(
            model_name='program',
            name='deadlines',
            field=models.ManyToManyField(to='directory.Deadline'),
        ),
        migrations.AddField(
            model_name='program',
            name='disciplines',
            field=models.ManyToManyField(to='directory.Discipline'),
        ),
        migrations.AddField(
            model_name='program',
            name='durations',
            field=models.ManyToManyField(to='directory.Duration'),
        ),
        migrations.AddField(
            model_name='university',
            name='ranking',
            field=models.ManyToManyField(to='directory.Ranking'),
        ),
    ]
